### ISSUE TITLE
[Issue] Power bank access issue

### ISSUE THREAD

**Issue by accessdenied0** [SleepyTrousers/EnderIO#2756]
Dear EnderIO developing-team,

I tried your newest version of EnderIO (1.7.10-2.3.0.410_beta) and got everytime I try to open (left-click) a "Power Bank" a crash. To be exact: 2 crash-reports: 
* Server: http://pastebin.com/ZMgDW6is 
* Client: http://pastebin.com/v6U2zwhe

I play on a SSP-world and I have to say I'm not sure if this crash is the fault of this mod, because nobody else seem to have the same issue.

thank you for all help,

access_denied

**Comment by tterrag1098** [comment]
Try updating EnderCore

**Comment by accessdenied0** [comment]
Hello @tterrag1098 

Thank you for your help but, 

I use already the newest version (1.7.10-0.1.0.21_beta) of EnderCore is or was there an update which I missed? (Like the Ender IO update which is unavailable now like it seems)

access_denied

**Comment by zzApotheosis** [comment]
Yeah, I was just about to post an issue with a server-side crash upon starting my SSP world, but looks like it was just fixed in 411_beta. Excellent work, @tterrag1098 and other devs!

**Comment by SnowShock35** [comment]
@zzApotheosis You sure? I'm still having that issue in version 2.3.0.411_beta (EnderCore version 0.1.0.21_beta)

**Comment by accessdenied0** [comment]
@zzApotheosis @SnowShock35,

I can confirm the main problem is still existing. Additional @zzApotheosis my issue has nothing to do with a crash upon startup. It is a crash by right-clicking a power bank. (I tried now different EnderIO blocks this crash happens only by power banks at it seems)

access_denied

**Comment by plazia** [comment]
Yes I too am running the latest beta. 

EnderIO-1.7.10-2.3.0.411_beta
EnderCore-1.7.10-0.1.0.21_beta

I cheated in a fully filled up vibrant capacitor bank via NEI, attempted to right click it and it instantly crashed both server and client.

Server crash report here http://hastebin.com/nayefuxumu.1c
Clicent crash report here http://hastebin.com/nisitibico.coffee

**Comment by SnowShock35** [comment]
I believe the error is occurring in EnderCore, not 100% sure though :confused:

**Comment by tterrag1098** [comment]
Fixed in 412
