### ISSUE TITLE
Experience Rod

### ISSUE THREAD

**Issue by zISKo666** [SleepyTrousers/EnderIO#3297]
The Experience Rod is not working for me since Ender IO 2.3.0.424 beta and is still brocken with .425 beta.

Can't input XP in a Soul Binder or any other tank with shift+right click.
Getting XP from the Soul Binder or a tank with just right clicking is working.

Back to .423 beta and everything is OK.

---
#### Affected Versions (tested):
- EnderIO: 2.3.0.424 beta / 2.3.0.425 beta
- EnderCore: 0.2.0.34 beta
- Minecraft: 1.7.10
- Forge: 10.13.4.1614 / 10.13.4.1558

**Comment by CrazyPants** [comment]
Fixed in 1.9.4

**Comment by HenryLoenwind** [comment]
working for me in 1.7.10.

**Comment by HenryLoenwind** [comment]
oh, I see. that's a bug in endercore that was fixed for 1.8 but not backported yet

**Comment by HenryLoenwind** [comment]
fixed in latest endercore

**Comment by zISKo666** [comment]
So I tested it with the latest 1.7.10 releases
-  EnderIO-1.7.10-2.3.0.426_beta 
-  EnderCore-1.7.10-0.2.0.35_beta

and it's still not working.

The only difference is that I can store XP in tanks again.
Storing XP to the Soul Binder dosn't work.

The combination of
-  EnderIO-1.7.10-2.3.0.423_beta
-  EnderCore-1.7.10-0.2.0.35_beta

is working.

I think it's a problem with EnderIO-1.7.10-2.3.0.424_beta and above.
