### ISSUE TITLE
Fluid Dupe with Cells

### ISSUE THREAD

**Issue by JasonMcRay** [SleepyTrousers/EnderIO#3302]
#### Issue Description:
If you partially fill an EnderIO tank with any fluid and then you will add other fluid via IC2 Cells into GUI, the cells will empty out into the tank raising the amount of the fluid in it.

#### What happens:
Cells containing other fluid than what is in the tank will empty out and raise the amount of liquid in the tank.

#### What you expected to happen:
Cells not emptying into tank containing different fluid than its in the tank. Not raising the amount of liquid in the tank

#### Steps to reproduce:

1. Put any fluid into the Tank (Fluid A) - For Example Water
2. Try to add more fluid (Fluid B, different than Fluid A) via the GUI of the tank using Universal Cells - Example Universal Cell containing Lava
3. ???
4. Watch the amount of Fluid A raise up even since the fluid inserted via cells (Fluid B) is totally different

Extra:
With GregTech installed it also happens with Cells from GT.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 2.3.0.425
- EnderCore: 0.2.0.33
- Minecraft: 1.7.10
- Forge: 1614
- IC2: 2.2.821

#### Your most recent log file where the issue was present: 
https://gist.github.com/JasonMcRay/8545240a60fcbb10fb392cea33b65ac0

**Comment by HenryLoenwind** [comment]
Already fixed for v3, it looked like a porting artifact. Seems it wasn't.

**Comment by JasonMcRay** [comment]
Also it seems that it happens with rightclicking for example OpenBlocks tank (with Fluid B) on the eIO tank containing Fluid A.

**Comment by HenryLoenwind** [comment]
fixed in latest EnderCore

**Comment by JasonMcRay** [comment]
@HenryLoenwind Unfortunately not. Still happening with:

eIO: 2.3.0.426
EnderCore: 0.2.0.35
MC: 1.7.10

Or is that EnderCore build with this fixed not out yet?

**Comment by HenryLoenwind** [comment]
that build was a dud, nothing's in there. build 36 will have the fix. sry.
