### ISSUE TITLE
[1.10.2] Aversion Obelisk not preventing baby skeleton spawns

### ISSUE THREAD

**Issue by xenoflot** [SleepyTrousers/EnderIO#3727]
#### Issue Description:
My server runs a slightly modified FTB Unstable 1.10. There's no support channel for that :-/ so I'm reporting here.

#### What happens:
Baby skeletons are spawning within the range of effect of an Aversion Obelisk.
* The obelisk contains a soul vial containing an unarmoured, adult skeleton.
* Have also tested with adding a vial containing baby skeleton but no change on results.

* The obelisk at my base is working fine with just the adult skeleton vial. The obelisks at spawn and my friend's base are still letting baby skels spawn (with and w/o the baby in a vial)

* All obelisks are fitted with a octadic capacitor and have reliable power.

* We considered the possibility that the skels walked in from outside the exclusion zone, but there are too many in close for that to be the case.

* Only thought that I've had is that interaction with Mekanism (since it gives armour to many mobs) may be the cause

#### What you expected to happen:
All mob sub-types to be prevented from spawning, if a vial containing any mob sub-type is present in the obelisk

#### Steps to reproduce:

1. Place and power an Aversion Obelisk
2. Add an Octadic Capacitor
3. Add soul vial containing a skeleton
4. Wait.

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: EnderIO-1.10.2-3.0.1.95_beta
- EnderCore: EnderCore-1.10.2-0.4.1.51-beta
- Minecraft: 1.10.2
- Forge: 12.18.1.2073
- Mekanism: Mekanism-1.10.2-9.2.0.292

#### Your most recent log file where the issue was present: 

I don't have access to server logs.

**Comment by HenryLoenwind** [comment]
Baby skeletons are not a vanilla mob. Do you happen to know which mod adds them?

**Comment by HenryLoenwind** [comment]
Found it, they are Mekanism, too.

And BTW, they are NOT a sub-type of Skeletons. So you will need a matching "baby skeleton" soul vial.

**Comment by xenoflot** [comment]
hmmm, I've personally tried the spawn obelisk with and without the baby skeleton soul vial, and my friend says he's tried with and without at his base.

Should I lodge with Aidan Brady or will you follow up with him?

**Comment by HenryLoenwind** [comment]
I'm currently trying to setup a dev env with both mods to run this through the debugger...

**Comment by HenryLoenwind** [comment]
Ok, I found the issue. The mobs pretend to be skeletons, but that only works while they exist in the world, not while they are stored in a soul vial. That's mostly harmless, up to the point where we need to compare them and find a "skeleton" that has a type (normal, wither, stray) in the world but some "not-skeleton" that has no type in the bottle.

The fix is to ignore the skeleton-type if the soul vial doesn't have a type.

**Comment by HenryLoenwind** [comment]
fixed in next build

**Comment by xenoflot** [comment]
You're good! You're _real_ good! Thanks Henry!

**Comment by xenoflot** [comment]
Hi Henry,

We're running 3.0.1.120_beta now and it appears that this problem still remains.
