### ISSUE TITLE
Ender IO - 1.12.2 - 5.0.28 Fatal Recipe Error

### ISSUE THREAD

**Issue by RyanP1991** [SleepyTrousers/EnderIO#4739]
#### Issue Description:

Game crashes on load with latest Ender IO / Ender Core due to an Ender IO Fatal Recipe Error.

#### What happens:

When the game is loading an ender io fatal recipe error occurs, attachted is a screenshot of what is displayed.

https://imgur.com/a/SrCorpr

Bad File - recipes/machines.xml 

Error Message - Could not find a crafting ingredient for 'enderio:block_omni_reservoir in <recipe> 'Omni Reservoi'

#### What you expected to happen:

The game not to crash while loading and to load up fully to the main menu.

#### Steps to reproduce:

1. Install Forge 14.23.4.2727 / Ender IO - 1.12.2-5.0.28 / Ender Core - 1.12.2 -0.5.35
2. Load up the game
3. Crash while loading
...

____
#### Affected Versions (Do *not* use "latest"):

- EnderIO: 1.12.2 - 0.5.28
- EnderCore: 1.12.2 - 0.5.35
- Minecraft: 1.12.2
- Forge: 14.23.4.2727

#### Your most recent log file where the issue was present: 

Log File attatched: 

https://pastebin.com/VUygsgKx

**Comment by Cheeyev** [comment]
I'm experiencing the same issue with the latest version as well. Somebody on the EnderIO Discord server said to delete "machines.xml" in the EnderIO config recipes folder, but that didn't resolve the problem.

**Comment by RyanP1991** [comment]
I saw that as well and tried deleting "machines.xml" so it regens the file and still causes the same crash.

**Comment by Cheeyev** [comment]
Yeah, I'm guessing it's an error with the default recipe inside the file or something. I also tried to regenerate the entire recipes folder, which didn't change anything.

**Comment by Wotzinator** [comment]
this problem seems to also appear in the modular version

**Comment by b52src** [comment]
im guessin there is an issue here(line 260-280), same recipe but looks like the omni is using name "blockGlass" instead of "blockGlassHardened" for the item name. Going to adjust this and see if that solves it.

`<recipe name="Reservoir" required="true">
    <crafting>
      <grid size="3x3">
        <item name="blockGlassHardened" /><item name="FUSED_QUARTZ" /><item name="blockGlassHardened" />
        <item name="blockGlassHardened" /><item name="item:minecraft:cauldron" /><item name="blockGlassHardened" />
        <item name="blockGlassHardened" /><item name="FUSED_QUARTZ" /><item name="blockGlassHardened" />
      </grid>
      <output name="enderio:block_reservoir" amount="4" />
    </crafting>
  </recipe>

  <recipe name="Omni Reservoir" required="true">
    <crafting>
      <grid size="3x3">
        <item name="blockGlass" /><item name="FUSED_QUARTZ" /><item name="blockGlass" />
        <item name="blockGlass" /><item name="item:minecraft:cauldron" /><item name="blockGlass" />
        <item name="blockGlass" /><item name="FUSED_QUARTZ" /><item name="blockGlass" />
      </grid>
      <output name="enderio:block_omni_reservoir" amount="4" />
    </crafting>
  </recipe>`

**Comment by LuciusV** [comment]
Same there on Forge 2705

**Comment by JasonKillsUs** [comment]
same here, Forge 2727

**Comment by TheSnowyChickens** [comment]
²

**Comment by Protheus** [comment]
changed blockGlass to blockGlassHardened as per b52src and that didnt work

**Comment by tyler489** [comment]
Try adding this to the user recipe 
```
  <recipe name="Omni Reservoir" required="false" disabled="true">
    <crafting>
      <grid size="3x3">
        <item name="blockGlass" /><item name="FUSED_QUARTZ" /><item name="blockGlass" />
        <item name="blockGlass" /><item name="item:minecraft:cauldron" /><item name="blockGlass" />
        <item name="blockGlass" /><item name="FUSED_QUARTZ" /><item name="blockGlass" />
      </grid>
      <output name="enderio:block_omni_reservoir" amount="4" />
    </crafting>
  </recipe>
```

**Comment by tyler489** [comment]
If the game launches fine then try adding this recipe
```
  <recipe name="Omni Reservoir" required="true">
    <crafting>
      <grid size="3x3">
        <item name="blockGlass" /><item name="FUSED_QUARTZ" /><item name="blockGlass" />
        <item name="blockGlass" /><item name="minecraft:cauldron" /><item name="blockGlass" />
        <item name="blockGlass" /><item name="FUSED_QUARTZ" /><item name="blockGlass" />
      </grid>
      <output name="enderio:block_omni_reservoir" amount="4" />
    </crafting>
  </recipe>

**Comment by d3radicated** [comment]
I think it has something to do with the output block `enderio:block_omni_reservoir`. I think the block is missing from the mod.

**Comment by LuciusV** [comment]
@tyler489 adding either of these recipes to user_recipes.xml doesn't help

**Comment by tyler489** [comment]
Adding the first one should have stoped it from crashing..

**Comment by TheSnowyChickens** [comment]
Nope, it still crash.

**Comment by JelleDijkhuizen** [comment]
yeah the file keeps resetting to default

**Comment by d3radicated** [comment]
Does the error have something to do with the latest commit (https://github.com/SleepyTrousers/EnderIO/commit/97e9c05aaafeb675e7b72e7fb91af138949dfd39)?

**Comment by kuroyure** [comment]
same error

**Comment by EpicSquid** [comment]
I have fixed this in the latest commit. It's uploading to curse now.

**Comment by EpicSquid** [comment]
Fix is out on curse now. https://minecraft.curseforge.com/projects/ender-io/files/2579152

**Comment by JayGaming8618** [comment]
its still doesn't work i'm using it with FTB's Sky Factory 3 and its always crashing i tried installing it from curse and deleting the old one but it just doesn't work please help me
